//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarWash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarClientSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarClientSet()
        {
            this.RecordSet = new HashSet<RecordSet>();
        }
    
        public string CarNumber { get; set; }
        public System.Guid ClientClientId { get; set; }
        public System.Guid CarCarId { get; set; }
        public Nullable<int> PriorityBox { get; set; }
        public Nullable<System.Guid> PriorityCarWasher { get; set; }
    
        public virtual Car CarSet { get; set; }
        public virtual Client ClientSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecordSet> RecordSet { get; set; }
    }
}
