//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarWash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentSet
    {
        public System.Guid PaymentId { get; set; }
        public System.DateTime DataTime { get; set; }
        public System.Guid OrderOrderId { get; set; }
    
        public virtual Order OrderSet { get; set; }
    }
}
