//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarWash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecordSet()
        {
            this.OrderSet = new HashSet<Order>();
        }
    
        public System.Guid RecordId { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<System.Guid> CarWasherCarWasherId { get; set; }
        public Nullable<int> BoxesBoxId { get; set; }
        public string CarClientCarNumber { get; set; }
        public string PriorityWasher { get; set; }
        public Nullable<int> PriorityBox { get; set; }
        public Nullable<int> NumberOfSeason { get; set; }
    
        public virtual Boxes BoxesSet { get; set; }
        public virtual CarClientSet CarClientSet { get; set; }
        public virtual CarWasher CarWasherSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> OrderSet { get; set; }
        public virtual Seasons Seasons { get; set; }
    }
}
