//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarWash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesByCategorySet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServicesByCategorySet()
        {
            this.OrderSet = new HashSet<Order>();
            this.OrderSet1 = new HashSet<Order>();
        }
    
        public System.Guid ServiceId { get; set; }
        public int Price { get; set; }
        public int Duration { get; set; }
        public int CategoryOfCarCategoryId { get; set; }
        public int ServicesCodeService { get; set; }
    
        public virtual CategoryOfCar CategoryOfCarSet { get; set; }
        public virtual Services ServicesSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> OrderSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> OrderSet1 { get; set; }
    }
}
