//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarWash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkSchedule
    {
        public System.Guid CarWasherId { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int NumberOfHours { get; set; }
    
        public virtual CarWasher CarWasherSet { get; set; }
    }
}
